### ISSUE TITLE
sbt 1.4.x seems to be required

### ISSUE THREAD

**Issue by sjrd** [scalacenter/scala3-migrate#149]
The readme says that the plugin requires sbt 1.3.x or above, but using 1.3.x yields the following error at load time:
```
[error] java.lang.NoSuchMethodError: sbt.Def$.ifS(Lsbt/internal/util/Init$Initialize;Lsbt/internal/util/Init$Initialize;Lsbt/internal/util/Init$Initialize;)Lsbt/internal/util/Init$Initialize;
```
Upgrading to sbt 1.4.x fixes that issue.

The readme should be updated, or we should actually make it work with 1.3.x.
